### ISSUE TITLE
[Suggestion] Better way to set cfg-lints

### ISSUE THREAD

**Issue by boozook** [AS1100K/pastey#13]
https://github.com/AS1100K/pastey/blob/18c2c9851ac25163a0b6d275961cf85541c45704/build.rs#L14-L15

According to the documentation for `cfg` ([for package] & [for workspace]) I'd prefer to set it this way instead of set it from the build-script that needs to be compiled, run, parse its output, etc. 
Just a little less CPU-time spent and heated air, as well as less code.

[for package]: https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section
[for workspace]: https://doc.rust-lang.org/stable/cargo/reference/workspaces.html#the-lints-table

- - -

This can be replaced with lint instructions in the cargo package manifest like this:
```toml
[lints.rust.unexpected_cfgs]
level = "deny" # deny other unexpected cfg queries
check-cfg = [
	'cfg(no_literal_fromstr)',                       # explain the reason for it,
	'cfg(feature, values("protocol_feature_paste"))' # or point where and for what it used
]
```
